# Generated by Django 5.1.4 on 2024-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acelerometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_actualizacion', models.IntegerField(default=50)),
                ('precision', models.FloatField(default=0.01)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_actualizacion', models.IntegerField(default=30)),
                ('resolucion', models.CharField(default='1920x1080', max_length=20)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ControladorDron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_x', models.FloatField(default=0.0)),
                ('posicion_y', models.FloatField(default=0.0)),
                ('posicion_z', models.FloatField(default=0.0)),
                ('velocidad_x', models.FloatField(default=0.0)),
                ('velocidad_y', models.FloatField(default=0.0)),
                ('velocidad_z', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Giroscopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_actualizacion', models.IntegerField(default=50)),
                ('precision', models.FloatField(default=0.01)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_actualizacion', models.IntegerField(default=1)),
                ('precision', models.FloatField(default=0.001)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
