# Generated by Django 5.1.4 on 2024-12-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0003_delete_acelerometro_delete_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='camara_fps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='gps_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='gps_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
