# Generated by Django 5.1.4 on 2024-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0007_delete_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='gps_alt',
            new_name='camera_x',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='gps_long',
            new_name='camera_y',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cam_vision',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='camera_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='gps_lon',
            field=models.FloatField(default=0),
        ),
    ]
