# Generated by Django 5.1.4 on 2024-12-18 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0008_rename_gps_alt_movimiento_camera_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_z',
            field=models.FloatField(default=0),
        ),
    ]
