# Generated by Django 5.1.4 on 2024-12-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0009_movimiento_timestamp_alter_movimiento_posicion_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='camera_z',
        ),
    ]
