# Generated by Django 5.1.4 on 2024-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0010_rename_timestamp_movimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='acelerometro_z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='camera_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='camera_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='giroscopio_z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='gps_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='gps_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_z',
            field=models.FloatField(),
        ),
    ]
